### ISSUE TITLE
panic: runtime error: index out of range [-32768]

### ISSUE THREAD

**Issue by yj12138** [arnodel/golua#108]
When I require a lua file that is over 100Kb in lua, I get an error message: panic: runtime error: index out of range [-32768] [recovered]
panic: runtime error: index out of range [-32768], is there any parameter setting?

**Comment by arnodel** [comment]
Hello, would you be able to give me the full traceback?

**Comment by arnodel** [comment]
Actually I can reproduce it easily, I have a PR to fix it.

**Comment by arnodel** [comment]
There is a release of Golua that fixes this (v0.1.0)
