### ISSUE TITLE
Implement io.popen()

### ISSUE THREAD

**Issue by arnodel** [arnodel/golua#7]

**Comment by sammy-ette** [comment]
hi, is there any specific thing holding this back? does it require a rework of what the file struct actually does instead of just wrapping a go file? i was going to implement it but don't really know how to

**Comment by arnodel** [comment]
I just never got round to implementing this. It is probably necessary to
modify the Golua File wrapper struct slightly, because Go's exec.Cmd gives
you access to the process's stdin via an io.WriteCloser rather than a file
handle (similar for stdout).  It could be easy enough because the Golua
File wrapper already has a Reader and a Writer that buffer access to the
file.

I could do this when I have some time (not sure exactly when right now). If
you would like to submit a PR that would also be great!
