### ISSUE TITLE
print traceback by default

### ISSUE THREAD

**Issue by sammy-ette** [arnodel/golua#90]
why don't errors print the traceback? anytime i get a lua error, it's only half useful since i don't know where it comes from

**Comment by arnodel** [comment]
You can show the traceback by using xpcall to register a custom message handler.  This is essentially what the repl does.

Here is a simple example, call it `test.lua`:

```lua
function bar(x) error("my error") end
function foo(x) bar(x) end

function handleError(msg) print(debug.traceback(msg, 2)) end

xpcall(foo, handleError, "hi")

```

```
$ golua test.lua
test.lua:1: my error
in function error (file [Go])
in function bar (file test.lua:1)
in function foo (file test.lua:3)
in function xpcall (file [Go])
in function <main chunk> (file test.lua:7)
```

**Comment by sammy-ette** [comment]
what about running a lua chunk from go? my use case is that i have hilbish running whatever lua code and in any case there's an error, a user shouldn't have to constantly use xpcall to get a backtrace.

i think this should be default behavior as well, right?

**Comment by arnodel** [comment]
In that case, you can set up the execution context so that a traceback is printed on error.  See for example how the simple repl does it:

https://github.com/arnodel/golua/blob/lua5.4/cmd.go#L250-L259

**Comment by sammy-ette** [comment]
ohhh ok thanks
